### ISSUE TITLE
OpenSSLCrypt.php

### ISSUE THREAD

**Issue by Pogorelyi** [cmnty/php-push#12] opened 2018-07-06 08:47 UTC
`$encryptedText = openssl_encrypt($plainText, 'aes-128-gcm', $contentEncryptionKey->getRawKeyMaterial(), OPENSSL_RAW_DATA, $nonce->getRawBytes(), $tag);`

undefined var **$tag**

**Comment by johanderuijter** [comment] 2018-07-06 12:00
`$tag` is passed by reference, see [openssl_encrypt](https://secure.php.net/manual/en/function.openssl-encrypt.php). It's used so the authentication tag can also be accessed outside of the scope of the method when using AEAD cipher mode as the method already returns the encrypted data and could not also return the tag.

Before passing it to the method, it does not need to be defined. Closing as this is deliberate and not a bug.

**Closed as completed by johanderuijter** 2018-07-06 12:00 UTC
