### ISSUE TITLE
Invalid data: only uncompressed keys are supported

### ISSUE THREAD

**Issue by snzmnrdn** [cmnty/php-push#8] opened 2016-11-22 04:55 UTC
I think this issue similar to https://github.com/web-push-libs/web-push-php/issues/12
Im not sure how to fix this

```
Type: InvalidArgumentException

Message: Invalid data: only uncompressed keys are supported.

Filename: /home/vagrant/Code/zxc/vendor/mdanter/ecc/src/Serializer/Point/UncompressedPointSerializer.php

Line Number: 49

Backtrace:
```

**Comment by johanderuijter** [comment] 2016-11-22 22:44
In order to help you, i will need more information.

Could you provide us with the code sample you are trying to run so we can reproduce the error?
Also, i will need the full error, including the backtrace so i know which call in this library ended up producing this error.

If i cannot reproduce the error, i cannot help you solve it.

**Comment by johanderuijter** [comment] 2016-12-07 21:13
Closing the issue for now, feel free to reopen when you have more information.

**Closed as completed by johanderuijter** 2016-12-07 21:13 UTC
